name: media_picker_widget
description: A widget that picks media files from storage and allows you to place anywhere in the widget tree.
version: 0.0.4
homepage: https://github.com/vankhai1997/media_picker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  photo_manager: ^2.2.1
  sliding_up_panel: ^2.0.0+1
  image_picker: ^0.8.3+2
  flutter_svg: ^1.0.3
  flick_video_player:
  visibility_detector:
  video_player:
  flutter_animator:
  rxdart:
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/ic_loading_image.svg
